{% set name = "constantly" %}
{% set version = "23.10.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa92b70a33e2ac0bb33cd745eb61776594dc48764b06c35e0efd050b7f1c7cbd

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - constantly

about:
  home: https://github.com/twisted/constantly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symbolic constants in Python
  description: |
    A library that provides symbolic constant support.
    It includes collections and constants with text, numeric, and bit flag values.
    Originally twisted.python.constants from the Twisted project.
  doc_url: http://constantly.readthedocs.io/en/latest
  dev_url: https://github.com/twisted/constantly

extra:
  recipe-maintainers:
    - isuruf
