{% set name = "constantly" %}
{% set version = "23.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/constantly-{{ version }}.tar.gz
  sha256: aa92b70a33e2ac0bb33cd745eb61776594dc48764b06c35e0efd050b7f1c7cbd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68.2
    - versioneer ==0.29
    - pip
  run:
    - python >=3.8

test:
  imports:
    - constantly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/twisted/constantly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symbolic constants in Python
  description: |
    A library that provides symbolic constant support.
    It includes collections and constants with text, numeric, and bit flag values.
    Originally twisted.python.constants from the Twisted project.
  doc_url: http://constantly.readthedocs.io/en/latest
  dev_url: https://github.com/twisted/constantly

extra:
  recipe-maintainers:
    - isuruf
