travis:
  secure:
    BINSTAR_TOKEN: IpRU56oWjnCV3PZ6z0I6Ora0XS/7chodlc51l3o7B8hmdV56asZ3QzzCFHMXeZ1jis/KKqBZQXeCeEZqz4ZhYX8kXoRViZeDzCJmw7hD1JR4beGgcstmRauQqXGx82vDZFuRtC1RUJl5kjuQPzV/h3aCzaiGZrGvw3u8oF4e78HDXGFJMQL5bcKOjPGKI0cUNxRpXB44q5OSeoBWgBWsP4cXmzoJluNZmVlD5FtGwFQDuscy3ia0euK0XuwKeTx3hSEhHuJpVAHabVoAvwlOsbvU9Nn3HKqV/HUo0iVebrTaQ6ZT1BVGSL7BulOVyeH9bBkxvRLpbrh4cf2dUnCuyWXcmN1rkHlBRKWUMLQ6RNWy/hLsADK+3PGkkVura9xjUe2B5rHTDsptSF67P5M5vjIjZxA1u451/09Kw5negN5G/93wWTArtX8S1Z+0AEI8iItY9e7ijZW+xNIiSiHDVwmTvhFr7n3F4FpyaCJeFm/mYihgAVtmJOoIXIGI8Q9mvh/F9XyAsy3vTnbBZexBDMrey9+zQkQhzrzLbjEaESxECEvulwHvOo6l0uMITf2FP+PakDG2XXd4GSkWJSAv18YuurxYVOi6YEL7sYoAzBDSFE2h0w7sXJgBxZ5noCxsVURuAGBPm6695+rEfYNaWgNnRDW8D9Uj8A9ZRRxtJgo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
